branches:
  only:
  - master
env:
  global:
    secure: "Ep+DoC9sMpdFWSF2vWQpLS/1TD6Aszvz27+zFLI6BCNDyRqRGK9jX1Xgv6ywgOlfpp+C4zNnoBRNq+OrrSRPiOiZJwg+Bb4k9lRndreb+Pf6taDBTKLUL2fQG6PXo1yBGTNJ4kfrIda5vq7u1ucDrHKyZ2OkoYXcTlV71nYiJj7rkpX7vIqStl++xTOAHUge0SznenjLADJluVtAN+ds4e5PYqB7+3oSHfMv2NIip/oZnQl3vBJKLw4OqjKdigM/poZS8oVX7lEL1tx8Zwtl+7VqrNqwz6M3Bd0x8s+Bw53xH2klPHFddKO7cVrH8vxfzmxbOT0dabiALDSDRzS4hnX2z/EUwxX3H89oqtGTGMgAW2HsYykiHbhwyJu+fiAeW73EngmEmoJSeZTfInwo3JxEdNqp2VoaC4kLBenVBigUzmi3/33fYdUwRI8e+JReoB/CCLkroPb7xGcdN789uDVys1nyQuyx4p++EDbBP71FiImKwKXDOpjc00xj+3eHFdknU6yAL1XL5VGxei32CH3sUdzFCv/V5F+JeVxHWo/51m8c6t2rvf6KSSP4Ypw/mdCmDB5s/5chthFNHX2A///arf2Srkiqj/NaEJ57YqTvx9cCYLvxkAnnUpQv/yvoV+xUChZA+PKjTPUfhPAzNuV/yqFAjBvT52y9T9e+8dw="
install:
- pip install ghp-import
language: python
script:
- make develop public gh-pages-commit gh-pages-push
sudo: false
